
# 1:product, 2:stage, 3:uat, 4:qa, 5:test
env.index: 5

channel.buffer.size: 100000

udp.addr: "0.0.0.0:36365"
# 9 * 1024 * 1024
udp.frame.max.size: 9437184

tcp.addr: "0.0.0.0:36366"
tcp.frame.max.size: 9437184
tcp.threads: 5

output.workers: 5

kafka:
  batch.size: 100
  topic: "rust-demo"
  brokers: "10.100.49.2:9092,10.100.49.3:9092,10.100.49.4:9092"
  compression.codec: "snappy"
  message.max.bytes: 9437184

