
# 1:product, 2:stage, 3:uat, 4:qa, 5:test
env.index: 5

tcp.threads: 5
output.workers: 5

kafka:
  topic: "rust-demo"
  brokers: "10.100.49.2:9092,10.100.49.3:9092,10.100.49.4:9092"
  compression.codec: "snappy"
  message.max.bytes: 9437184

